[package]
name = "net_comms"
version = "0.1.0"
authors = ["stepa <pamallinos@email.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
library = {path = "library"}
lib = {path = "lib"}

utils = {git = "https://github.com/WellHereIAm/utils.git", branch = "main"}
serde = { version = "1.0", features = ["derive"] }
ron = "*"
